In [1]:
import numpy as np
import torch

In [2]:
# Input (temp, rainfall, humidity)
ninputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]], dtype='float32')

# Targets (apples, oranges)
ntargets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119]], dtype='float32')

In [3]:
inputs = torch.from_numpy(ninputs)
targets = torch.from_numpy(ntargets)

weights = torch.randn(2, 3, requires_grad=True)
bias = torch.randn(2, requires_grad=True)
weights, bias

(tensor([[ 1.5495, -0.1725,  0.8926],
         [-0.6080,  1.1444, -0.0593]], requires_grad=True),
 tensor([ 0.3104, -0.7015], requires_grad=True))

In [4]:
def LRmodel(x):
    return x @ weights.t() + bias # @matrix multiplication

In [5]:
def mse(t1, t2):
    diff = t1 - t2
    return torch.sum(diff ** 2) / diff.numel()

In [6]:
preds = LRmodel(inputs)
loss = mse(preds, targets); loss

tensor(6085.6089, grad_fn=<DivBackward0>)

In [7]:
loss.backward()

In [8]:
print(weights)
print(weights.grad)

tensor([[ 1.5495, -0.1725,  0.8926],
        [-0.6080,  1.1444, -0.0593]], requires_grad=True)
tensor([[ 7866.6436,  6484.6006,  4453.6108],
        [-4177.7031, -4117.5967, -2720.5786]])


In [9]:
print(weights)
print(weights - weights.grad * 1e-5)

tensor([[ 1.5495, -0.1725,  0.8926],
        [-0.6080,  1.1444, -0.0593]], requires_grad=True)
tensor([[ 1.4709, -0.2374,  0.8481],
        [-0.5662,  1.1855, -0.0321]], grad_fn=<SubBackward0>)


In [10]:
with torch.no_grad(): #(torch) do not track this calculation-
    weights -= weights.grad * 1e-5
    bias -= bias.grad * 1e-5

In [11]:
weights, bias

(tensor([[ 1.4709, -0.2374,  0.8481],
         [-0.5662,  1.1855, -0.0321]], requires_grad=True),
 tensor([ 0.3095, -0.7010], requires_grad=True))

In [12]:
preds = LRmodel(inputs)
loss = mse(preds, targets); loss

tensor(4576.3867, grad_fn=<DivBackward0>)

In [13]:
weights.grad.zero_()
bias.grad.zero_()
print(weights.grad)
print(bias.grad)

# finish one epoch in Linear Regresion
# # # 

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([0., 0.])


In [14]:
for i in range(1000):
    preds = LRmodel(inputs)
    loss = mse(preds, targets)
    loss.backward()
    with torch.no_grad(): #(torch) do not track this calculation-
        weights -= weights.grad * 1e-5
        bias -= bias.grad * 1e-5
        weights.grad.zero_()
        bias.grad.zero_()

In [15]:
loss

tensor(7.0338, grad_fn=<DivBackward0>)

In [16]:
preds

tensor([[ 57.2022,  70.4885],
        [ 82.5436,  98.2114],
        [117.8686, 138.2597],
        [ 21.0433,  38.4736],
        [102.5863, 113.8724]], grad_fn=<AddBackward0>)

In [17]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

NameError: name 'nn' is not defined